version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: api_chat_web
    ports:
      - "8086:80"  # Ubah port eksternal ke 8083
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mysql-phpmyadmin

  app:
    container_name: api_chat_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    networks:
      - mysql-phpmyadmin
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: api_chat_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_chat
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data: