version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "8084:80"  # Ubah port eksternal ke 8083
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks: 
      - mysql-phpmyadmin

  app:
    # image: coba-up-docker-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    command: sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh && php-fpm"
    volumes:
      - ./:/var/www/html
    networks:
      - mysql-phpmyadmin

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin: